### ISSUE TITLE
training the network on ground-truth  

### ISSUE THREAD

**Issue by lasandcris** [piiswrong/deep3d#17]
I'd like to train the network using depth maps as ground truths. is that somehow possible - and if yes, can someone give me some pointers? thanks, laszlo

**Comment by piiswrong** [comment]
It's possible. remove the selection layer and quantize your depth map.

**Comment by lasandcris** [comment]
@piiswrong 
could you please run through how to use the train.py?
thanks

**Comment by zedomel** [comment]
How to use train.py? I'm trying to create a database using parse.py and data.py but I got this error when run: 
`python parse.py movie.avi exp` 

`Traceback (most recent call last):
  File "parse.py", line 204, in <module>
    process_movie2d(args.path, args.prefix)
  File "parse.py", line 184, in process_movie2d
    rect = list(get_clip_rect(fname, True))
  File "parse.py", line 141, in get_clip_rect
    assert cap.read()[0]
AssertionError`

What should be the movie specs? For run parse.py and then train.py?

**Comment by lwkobe** [comment]
@zedomel Have you solved your problem? If you use the anaconda, you will find the conda-opencv3 which can't read a video. I  am solving this problem.
