### ISSUE TITLE
Erro while training 

### ISSUE THREAD

**Issue by zedomel** [piiswrong/deep3d#27]
I had create a database using parse.py and data.py, but when I run train.py I got this error:

`$  python train.py 
[01:08:37] include/dmlc/logging.h:235: [01:08:37] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "vgg16-0001.params"
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    train(64, 'exp/deep3d')
  File "train.py", line 65, in train
    vgg16 = data.load_vgg(data_frames, flow_frames, two_stream=False)
  File "/home/salim/deep3d/data.py", line 443, in load_vgg
    vgg16 = {name: arr for name, arr in mx.nd.load('vgg16-0001.params').items() if name.startswith('arg:conv')}
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 956, in load
    ctypes.byref(names)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [01:08:37] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "vgg16-0001.params"
`

What file is that vgg16-0001.params???? What have to do make it work?
Thanks.

**Comment by zedomel** [comment]
OK...I found the VGG models and I used mxnet/tools/convert_caffe to create vgg16 files. Closed!

**Comment by lwkobe** [comment]
@zedomel  could you tell some detail how convert_caffe create the   vgg16 files? Thank you !

**Comment by lwkobe** [comment]
@zedomel   I get

**Comment by lwkobe** [comment]
@zedomel  could you tell me your email?

**Comment by zedomel** [comment]
Sorry @lwkobe, but you should use Github. It allows tracking and could help others users. Write a issue.

**Comment by lwkobe** [comment]
@zedomel  HI  when i  run the  train.py , i met a problem



[04:53:10] /home/hadasi/mxnet/dmlc-core/include/dmlc/./logging.h:235: [04:53:10] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    train(64, 'exp/deep3d')
  File "train.py", line 89, in train
    eval_data          = test_data)
  File "/home/hadasi/mxnet/python/mxnet/model.py", line 787, in fit
    sym_gen=self.sym_gen)
  File "/home/hadasi/mxnet/python/mxnet/model.py", line 188, in _train_multi_device
    logger=logger)
  File "/home/hadasi/mxnet/python/mxnet/executor_manager.py", line 311, in __init__
    self.slices, train_data)
  File "/home/hadasi/mxnet/python/mxnet/executor_manager.py", line 224, in __init__
    shared_data_arrays=self.shared_data_arrays[i])
  File "/home/hadasi/mxnet/python/mxnet/executor_manager.py", line 177, in _bind_exec
    grad_req=grad_req, shared_exec=base_exec)
  File "/home/hadasi/mxnet/python/mxnet/symbol.py", line 839, in bind
    ctypes.byref(handle)))
  File "/home/hadasi/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [04:53:10] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory
[04:53:10[04:53:10] /home/hadasi/mxnet/dmlc-core/include/dmlc/logging.h:235: [04:53:10] /home/hadasi/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR
] /home/hadasi/mxnet/dmlc-core/include/dmlc/logging.h:235: [04:53:10] /home/hadasi/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR
terminate called recursively

Did you met and could you tell me what i should do ?
Thank you !
