### ISSUE TITLE
Cannot find Operator CuDNNBatchNorm in registry

### ISSUE THREAD

**Issue by tzatter** [piiswrong/deep3d#3]
[12:38:08] /root/mxnet/dmlc-core/include/dmlc/logging.h:245: [12:38:08] src/operator/operator.cc:19: Cannot find Operator CuDNNBatchNorm in registry
Traceback (most recent call last):
  File "myMain.py", line 23, in <module>
    model = mx.model.FeedForward.load('deep3d', 50, mx.gpu(0))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 822, in load
    symbol, arg_params, aux_params = load_checkpoint(prefix, epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 362, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 886, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op bn_pool1 of type CuDNNBatchNorm: [12:38:08] src/operator/operator.cc:19: Cannot find Operator CuDNNBatchNorm in registry

cuda7.5 cudnn4
running by official mxnet docker gpu image

Thank you piiswrong

**Comment by Trangle** [comment]
the same problem!

**Comment by jtoy** [comment]
I get the same exact error

**Comment by piiswrong** [comment]
The official mxnet image doesn't have cuDNN. You need to download cuDNN and recompile MXNet with USE_CUDNN = 1 added to mxnet/config.mk

**Comment by jtoy** [comment]
I'm testing on a docker image with CudNN4 and cuda 7.5.  I've tried with adding CUDNN=1 and recompiling, but still getting the same error. I'll test more.

**Comment by piiswrong** [comment]
@jtoy  I forgot to mention that you also need to pull the most recent MXNet code. CuDNNBatchNorm is added recently.

**Comment by jtoy** [comment]
@piiswrong I'm pulling straight from source on mxnet:

git clone --recursive https://github.com/dmlc/mxnet /root/mxnet
git clone https://github.com/piiswrong/deep3d experiment
echo "EXTRA_OPERATORS=/root/experiment/operators\nCUDNN = 1" >> /root/mxnet/make/config.mk
cp /root/mxnet/make/config.mk /root/mxnet
cd /root/mxnet; make -j4
cd python; sudo python setup.py install

**Comment by piiswrong** [comment]
Sorry, my mistake. It's USE_CUDNN=1 instead of CUDNN=1.

**Comment by kuyun-zhangyang** [comment]
the same error!
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    model = mx.model.FeedForward.load('deep3d', 50, mx.gpu(0))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 822, in load
    symbol, arg_params, aux_params = load_checkpoint(prefix, epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 362, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 886, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op bn_pool1 of type CuDNNBatchNorm: [15:39:18] src/operator/operator.cc:19: Cannot find Operator CuDNNBatchNorm in registry

**Comment by tzatter** [comment]
Still I can't be running it
If anyone has successfully installed it, please let me know your environment setting

**Comment by tzatter** [comment]
Omg! I had forgotten python setup.py install after recompiling
maybe kuyun-zhangyang is also
everything is ok!
Can I close this thread?

**Comment by Greenleaf88** [comment]
I got this error:
mxnet.base.MXNetError: [19:49:17] src/operator/cudnn_batch_norm.cc:20: CuDNNBatchNorm is merged into BatchNorm for cudnn version above v5.Use the later instead.

What can I do?

**Comment by ZhengzhongSun** [comment]
How to python setup.py install after recompiling?
